### ISSUE TITLE
Socket Container.

### ISSUE THREAD

**Issue by AlexeiBuzuma** [AlexeiBuzuma/LocalComputeNetworks#11]
When calling 'select' function we need in separated list with sockets for reading and writing. 
So, socket container need contains this sockets with some meta information. ( Should be implemented functions like "**get_all_sockets_for_read** and **get_all_sockets_for_write**")
I think that this functionality very similar with **Session** and **SessionManager**. 

Maybe it makes sense to include information about sockets in **Session** class and implement functions for getting sockets in **SessionManager** class and ignoring fact about duplicating sockets with UDP mode?

Otherwise we will need in functionality for managing sockets.

**Comment by zaja1kun** [comment]
UDP plugin must be complex and have it's own implementation of SessionManager (overload get_all_sockets_for_read and get_all_sockets_for_write). I think we should implement a base class for SessionManager were these functions will be abstract.
